version: '3.8'
services:
  macos-sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    platform: linux/x86_64
    ports:
      - "1433:1433"
    volumes:
      - macos-sql-server:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "{YOUR_PASSWORD}"
volumes:
  macos-sql-server: